- name: Install nginx
  hosts: web
  become: true
  tasks:
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        state: installed

    - name: start httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes

- name: Install nginx
  hosts: web
  become: true
  roles:
    - sample