- name: Install nginx
  hosts: web
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: start nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

- name: install Nginx
  hosts: app
  become: true
  roles:
    - sample
