- name: vars Types
  hosts: localhost
  become: true
  vars:
    fruit: apple #string
    quantity: 100 #number
    for_sale: true
  tasks:
    - name: print
      ansible.builtin.debug:
        msg: Fruitname-{{fruit}}, Quantity-{{quantity}}
      when: for_sale