- name: Demo on loops
  hosts: all
  vars:
    fruits:
      - apple
      - orange
  tasks:
    - name: print fruits
      ansible.builtin.debug:
        msg: fruit name - {{item}}
      loop: "{{fruits}}"

    - name: print fruits
      ansible.builtin.debug:
        msg: fruit name - {{item}}
      loop:
        - apple
        - kiwi